title: "PINEAPPLE: Explainable AI for hyperspectral image analysis"
description: ""

timezone: Europe/Warsaw

navigation:
  Project: "#project"
  Team: "#team"
  Results: "#results"
  Contact: "#contact"
  ğŸš€ KP Labs: https://kplabs.space
  ğŸ¤– MI2.AI: https://www.mi2.ai
  ğŸ›°ï¸ ESA: https://philab.esa.int

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag
  - jekyll-spaceship

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
